version: '3'
services:

  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    networks:
      - backend
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d:ro
      - db_data:/data/db

  api:
    build: api
    restart: always
    container_name: api
    environment:
      API_PORT: ${API_PORT}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_URI: ${MONGO_URI}
    volumes:
      - /app/node_modules
      - ./api:/app
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - backend
      - frontend
    depends_on:
      - mongodb

  frontend:
    build: frontend
    restart: always
    container_name: frontend
    environment:
      API_URL: ${API_URL}
    volumes:
      - /app/node_modules
      - ./frontend:/app
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - frontend
    depends_on:
      - api

volumes:
  db_data:

networks:
  backend:
  frontend:
